import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";

const ubuntuRegular = localFont({
  src: "./fonts/Ubuntu-Regular.ttf",
  variable: "--font-ubuntu-regular",
  weight: "100 900",
});
const ubuntuMedium = localFont({
  src: "./fonts/Ubuntu-Medium.ttf",
  variable: "--font-ubuntu-medium",
  weight: "100 900",
});
const ubuntuBold = localFont({
  src: "./fonts/Ubuntu-Bold.ttf",
  variable: "--font-ubuntu-bold",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={`${ubuntuRegular.variable} ${ubuntuMedium.variable} ${ubuntuBold.variable} antialiased`}
        >
          {children}
        </body>
      </Providers>
    </html>
  );
}
